// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_TnBkXmIDudDgiZioTdzcJJU2d1RuOgQ',
    appId: '1:411399692835:web:d8a886560b9ba3c376c796',
    messagingSenderId: '411399692835',
    projectId: 'elak-admin-14b88',
    authDomain: 'elak-admin-14b88.firebaseapp.com',
    storageBucket: 'elak-admin-14b88.firebasestorage.app',
    measurementId: 'G-HW1F6L5RT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkYl6tW1hKGaWk4IlrPdPz_iXWkU6SR4U',
    appId: '1:411399692835:android:0a5df3ab0c03d8c076c796',
    messagingSenderId: '411399692835',
    projectId: 'elak-admin-14b88',
    storageBucket: 'elak-admin-14b88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhkfJXV1lf_j-FVpKcfMbn5sxodfZkzH8',
    appId: '1:411399692835:ios:0337f6a1274408a976c796',
    messagingSenderId: '411399692835',
    projectId: 'elak-admin-14b88',
    storageBucket: 'elak-admin-14b88.firebasestorage.app',
    iosBundleId: 'com.arabivalue.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_TnBkXmIDudDgiZioTdzcJJU2d1RuOgQ',
    appId: '1:411399692835:web:edf43a33eebf3b4276c796',
    messagingSenderId: '411399692835',
    projectId: 'elak-admin-14b88',
    authDomain: 'elak-admin-14b88.firebaseapp.com',
    storageBucket: 'elak-admin-14b88.firebasestorage.app',
    measurementId: 'G-28J9SHDK04',
  );
}